# shellcheck shell=bash disable=SC1091
# /etc/bashrc

# System wide functions and aliases
# Environment stuff goes in /etc/profile

# It's NOT a good idea to change this file unless you know what you
# are doing. It's much better to create a custom.sh shell script in
# /etc/profile.d/ to make custom changes to your environment, as this
# will prevent the need for merging in future updates.

# Prevent doublesourcing
if [ -z "$PROFILESOURCED" ] && [ "$PS1" ]; then
  PROFILESOURCED="Y"
  . /etc/profile
fi

if [ -z "$BASHRCSOURCED" ]; then
  BASHRCSOURCED="Y"

  # are we an interactive shell?
  if [ "$PS1" ]; then
    # Turn on parallel history
    shopt -s histappend
    # Turn on checkwinsize
    shopt -s checkwinsize
  fi
  STARSHIP_CONFIG=/etc/starship.toml
  export STARSHIP_CONFIG
  eval "$(starship init bash)"

  # Enable fzf keybindings
  [ -r /run/host/usr/share/fzf/shell/key-bindings.bash ] && \
  . /run/host/usr/share/fzf/shell/key-bindings.bash

  # Enable atuin and bash-prexec
  source /usr/share/bash-prexec
  eval "$(atuin init bash)"
fi

# vim:ts=4:sw=4
